FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV UV_HTTP_TIMEOUT=300

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY . .

# Install CPU-only PyTorch first
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

# Install remaining dependencies
RUN uv sync --no-dev

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "backend.main:app" ,"--host", "0.0.0.0", "--port", "8000"]